name: Build the app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install node
        run: npm i @zeppos/zeus-cli -g
      - name: build the APp
        working-directory: ./App
        run: echo | zeus build
      - uses: actions/upload-artifact@v3
        with:
          name: TOTP_Authenticator
          path: ./App/dist/*.zab
