name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        
    steps:
      - uses: actions/checkout@v3
      - name: Build the App
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: App
      - run: npm i @zeppos/zeus-cli -g
      - run: zeus build
